// <auto-generated />
namespace Project_Satish.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class prod_app : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prod_app));
        
        string IMigrationMetadata.Id
        {
            get { return "202303061849518_prod_app"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
